name: my-github-actions-lab 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      
jobs:
  terraforms:
    runs-on: ubuntu-latest
    steps:
      - name: Event Name
        run: echo ${{ github.event_name }}
      
      - name: Clone Code  
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init  
        run: terraform init

      - name: Terraform Format  
        run: terraform fmt 

      - name: Terraform Plan  
        run: terraform plan
        if: github.event_name == 'workflow_dispatch'

      - name: Terraform Apply  
        run: terraform apply --auto-approve
        if: github.event_name == 'workflow_dispatch'

